import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Title from '@/components/title/Title'
import Card from '@/components/card/Card'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <Title>salam</Title>
          <section className={styles.container}>
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          {/* <Card title='salam man f' image='/assets/1.jpeg' /> */}
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          <Card title='salam man f' image='/assets/1.jpeg' />
          </section>
      </main>
    </>
  )
}
